# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from helcim_python_sdk import Helcim

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        helcim = Helcim(
        
                        api_access_auth = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(helcim)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
