# coding: utf-8
"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from helcim_python_sdk.client_custom import ClientCustom
from helcim_python_sdk.configuration import Configuration
from helcim_python_sdk.api_client import ApiClient
from helcim_python_sdk.type_util import copy_signature
from helcim_python_sdk.apis.tags.card_batch_api import CardBatchApi
from helcim_python_sdk.apis.tags.card_terminal_api import CardTerminalApi
from helcim_python_sdk.apis.tags.card_transaction_api import CardTransactionApi
from helcim_python_sdk.apis.tags.customer_api import CustomerApi
from helcim_python_sdk.apis.tags.general_api import GeneralApi
from helcim_python_sdk.apis.tags.helcim_pay_api import HelcimPayApi
from helcim_python_sdk.apis.tags.invoice_api import InvoiceApi
from helcim_python_sdk.apis.tags.payment_api import PaymentApi



class Helcim(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.card_batch: CardBatchApi = CardBatchApi(api_client)
        self.card_terminal: CardTerminalApi = CardTerminalApi(api_client)
        self.card_transaction: CardTransactionApi = CardTransactionApi(api_client)
        self.customer: CustomerApi = CustomerApi(api_client)
        self.general: GeneralApi = GeneralApi(api_client)
        self.helcim_pay: HelcimPayApi = HelcimPayApi(api_client)
        self.invoice: InvoiceApi = InvoiceApi(api_client)
        self.payment: PaymentApi = PaymentApi(api_client)
