# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import helcim_python_sdk
from helcim_python_sdk.model.invoice_list_response import InvoiceListResponse
from helcim_python_sdk import configuration


class TestInvoiceListResponse(unittest.TestCase):
    """InvoiceListResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
