# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import helcim_python_sdk
from helcim_python_sdk.model.customer_request import CustomerRequest
from helcim_python_sdk import configuration


class TestCustomerRequest(unittest.TestCase):
    """CustomerRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
