# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import helcim_python_sdk
from helcim_python_sdk.model.invoice_create import InvoiceCreate
from helcim_python_sdk import configuration


class TestInvoiceCreate(unittest.TestCase):
    """InvoiceCreate unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
