# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.address import Address

class RequiredBankAccountResponse(TypedDict):
    pass

class OptionalBankAccountResponse(TypedDict, total=False):
    # The id of the bank account.
    id: int

    # The id of the customer owning the bank account.
    customerId: int

    # The date when the bank account is created.
    dateCreated: str

    # The date when the bank account last got updated.
    dateUpdated: str

    # The date when the bank account last got used.
    dateLastUsed: str

    # The date when the bank account is verified.
    dateVerified: str

    # The token of the bank account.
    bankToken: str

    # The type of the bank account, such as CHECKING | SAVINGS.
    accountType: str

    # The corporate type of the bank account, such as PERSONAL | CORPORATE.
    accountCorporate: str

    # Verified status of the bank account, 1|0.
    verified: str

    # Ready status of the bank account, 1|0.
    ready: str

    # The institution number of Canadian Bank Account that identifies the bank.
    bankIdNumber: str

    # The transit number of Canadian Bank Account. Shows which branch you opened your account at.
    transitNumber: str

    # The routing number of US Bank Account. Identifies the financial institution on which it was drawn.
    routingNumber: str

    # Last 4 digits of the bank account number.
    bankAccountNumberL4: str

    address: Address

class BankAccountResponse(RequiredBankAccountResponse, OptionalBankAccountResponse):
    pass
