# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBankAccount(TypedDict):
    # The bank account holder first name
    firstName: str

    # The bank account holder last name
    lastName: str

    # The company name
    companyName: str

    # Bank account number
    bankAccountNumber: str

    # CHECKING - Chequing, SAVINGS - Savings
    accountType: str

    # PERSONAL - Personal Bank Account, CORPORATE - Corporate Bank Account
    accountCorporate: str

    streetAddress: str

    city: str

    # Only allow CAN - Canada, USA - United States
    country: str

    province: str

    postalCode: str

class OptionalBankAccount(TypedDict, total=False):
    # Required for Canadian Bank Account Holder, the institution number - three digits - identifies your bank.
    bankIdNumber: str

    # Required for Canadian Bank Account Holder, the transit number - five digits - shows which branch you opened your account at.
    transitNumber: str

    # Required for US Bank Account Holder, a nine-digit code printed on the bottom of checks to identify the financial institution on which it was drawn.
    routingNumber: str

    # Customer given permission for a company or financial institution to debit a bank account when the payment is due.
    padAgreement: bool

class BankAccount(RequiredBankAccount, OptionalBankAccount):
    pass
