# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCardTerminalsRequest(TypedDict):
    pass

class OptionalCardTerminalsRequest(TypedDict, total=False):
    # The abbreviation of card terminal's currency. Possible values are CAD | USD
    currency: str

    # The card terminal's status. possible values are ACTIVE | INACTIVE
    status: str

class CardTerminalsRequest(RequiredCardTerminalsRequest, OptionalCardTerminalsRequest):
    pass
