# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCardToken(TypedDict):
    # The token for the card on file. If Customer Code is filled, The card should must be owned by a passed customer code
    cardToken: str

class OptionalCardToken(TypedDict, total=False):
    pass

class CardToken(RequiredCardToken, OptionalCardToken):
    pass
