# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCardResponse(TypedDict):
    pass

class OptionalCardResponse(TypedDict, total=False):
    # The id of the card.
    id: int

    # The card token.
    cardToken: str

    # The date when the card is created.
    dateCreated: str

    # The date when the card last got updated.
    dateUpdated: str

    # The cardholder name.
    cardHolderName: str

    # The first-six and last-four card numbers.
    cardF6L4: str

    # The card expiry date, in MMYY format (total of 4 digits without spaces or slashes).
    cardExpiry: str

    # The card CVV (3-4 digits on back of credit card).
    cardCVV: str

class CardResponse(RequiredCardResponse, OptionalCardResponse):
    pass
