# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCard(TypedDict):
    # The full card number (13 to 16 digits) from merchant to process \"purchase\", \"pre-auth\", and \"verify\" transactions.
    cardNumber: str

    # The card expiry date, in MMYY format (total of 4 digits without spaces or slashes).
    cardExpiry: str

    # The card CVV (3-4 digits on back of credit card).
    cardCVV: str

class OptionalCard(TypedDict, total=False):
    pass

class Card(RequiredCard, OptionalCard):
    pass
