# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCardTerminalAddress(TypedDict):
    pass

class OptionalCardTerminalAddress(TypedDict, total=False):
    street1: str

    street2: str

    city: str

    # Abbreviation of province
    province: str

    # Abbreviation of country
    country: str

    # Postal or zip code
    postalCode: str

class CardTerminalAddress(RequiredCardTerminalAddress, OptionalCardTerminalAddress):
    pass
