# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.card_terminal_address import CardTerminalAddress

class RequiredCardTerminal(TypedDict):
    pass

class OptionalCardTerminal(TypedDict, total=False):
    # Id of the terminal.
    id: int

    # Nickname of terminal
    nickname: str

    # Currency of terminal. possible values are CAD | USD
    currency: str

    # Status of Terminal. possible values are ACTIVE | INACTIVE
    status: str

    address: CardTerminalAddress

class CardTerminal(RequiredCardTerminal, OptionalCardTerminal):
    pass
