# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCardBatch(TypedDict):
    pass

class OptionalCardBatch(TypedDict, total=False):
    # Id of Card batch
    id: int

    # Date Card batch is Created
    dateCreated: str

    # Date Card batch is last updated
    dateUpdated: str

    # Date Card Batch is closed
    dateClosed: str

    # True if the batch is closed. Else false
    closed: bool

    # Id of associated Terminal
    terminalId: int

    # Batch Number
    batchNumber: int

    # Approved sales net refunds and voids
    netSales: typing.Union[int, float]

    # Gross sales
    totalSales: typing.Union[int, float]

    # Gross refunds
    totalRefunds: typing.Union[int, float]

    # Voided amount
    totalReversed: typing.Union[int, float]

    # Amount of voided refunds
    totalRefundsReversed: typing.Union[int, float]

    # Total number of transactions
    countTotal: typing.Union[int, float]

    # Number of approved transactions
    countApproved: typing.Union[int, float]

    # Number of declined transactions
    countDeclined: typing.Union[int, float]

class CardBatch(RequiredCardBatch, OptionalCardBatch):
    pass
