# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCheckoutInit200Response(TypedDict):
    pass

class OptionalCheckoutInit200Response(TypedDict, total=False):
    # The checkout token is used to initialize Helcim Pay
    checkoutToken: str

    # The secret token is used to validate the transaction response
    secretToken: str

class CheckoutInit200Response(RequiredCheckoutInit200Response, OptionalCheckoutInit200Response):
    pass
