# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.address import Address

class RequiredCustomerRequest(TypedDict):
    pass

class OptionalCustomerRequest(TypedDict, total=False):
    # The unique customer code. If blank, it will be automatically generated.
    customerCode: str

    # The primary contact name (full name) of the customer.
    contactName: str

    # The business name of the customer. There must be either a contact name or business name present.
    businessName: str

    # The cell phone number of the customer.
    cellPhone: str

    billingAddress: Address

    shippingAddress: Address

class CustomerRequest(RequiredCustomerRequest, OptionalCustomerRequest):
    pass
