# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.address import Address
from helcim_python_sdk.type.card1 import Card1

class RequiredCustomer(TypedDict):
    pass

class OptionalCustomer(TypedDict, total=False):
    # Id of Customer
    id: int

    # Customer code of the customer
    customerCode: str

    # Name of the business
    businessName: str

    # Contact Name
    contactName: str

    # Cell phone number of customer
    cellPhone: str

    billingAddress: Address

    shippingAddress: Address

    # Array of cards stored in the vault associated with this customer.
    cards: typing.List[Card1]

class Customer(RequiredCustomer, OptionalCustomer):
    pass
