# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.discount import Discount
from helcim_python_sdk.type.line_item import LineItem
from helcim_python_sdk.type.pickup import Pickup
from helcim_python_sdk.type.shipping import Shipping
from helcim_python_sdk.type.tax import Tax

class RequiredInvoiceCreateAfterProcessing(TypedDict):
    pass

class OptionalInvoiceCreateAfterProcessing(TypedDict, total=False):
    shipping: Shipping

    pickup: Pickup

    tax: Tax

    discount: Discount

    lineItems: typing.List[LineItem]

class InvoiceCreateAfterProcessing(RequiredInvoiceCreateAfterProcessing, OptionalInvoiceCreateAfterProcessing):
    pass
