# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.address import Address

class RequiredInvoiceCreate(TypedDict):
    pass

class OptionalInvoiceCreate(TypedDict, total=False):
    # Unique customer Id.
    customerId: int

    # The currency abbreviation of the invoice, such as CAD or USD. This should match currency of existing invoice.
    currency: str

    # The type of the invoice, such as ESTIMATE | INVOICE | QUOTE | ORDER | PURCHASE_ORDER | STATEMENT | REGISTRATION | CREDIT.
    type: str

    # The status of invoice, such as DUE | SHIPPED | COMPLETED | CANCELLED
    status: str

    billingAddress: Address

class InvoiceCreate(RequiredInvoiceCreate, OptionalInvoiceCreate):
    pass
