# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredInvoice(TypedDict):
    pass

class OptionalInvoice(TypedDict, total=False):
    # Date the invoice is created.
    dateCreated: str

    # Date the invoice is updated.
    dateUpdated: str

    # Date the invoice is paid.
    datePaid: str

    # Date the invoice is paid.
    dateIssued: str

    # The status of the invoice, such as due | paid | completed | refunded.
    status: str

    # The id of customer associated to the invoice.
    customerId: int

    # The total amount of the invoice.
    amount: typing.Union[int, float]

    # The total convenience fee paid for the invoice.
    convenienceFee: typing.Union[int, float]

class Invoice(RequiredInvoice, OptionalInvoice):
    pass
