# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredLineItem(TypedDict):
    description: str

    # The quantity of the line item. Can have upto 2 decimal places
    quantity: typing.Union[int, float]

    price: typing.Union[int, float]

    # Total = Price * Quantity
    total: typing.Union[int, float]

class OptionalLineItem(TypedDict, total=False):
    sku: str

    # This will be added to Invoice's total tax amount
    taxAmount: typing.Union[int, float]

    # This will be added to Invoice's total discount amount
    discountAmount: typing.Union[int, float]

class LineItem(RequiredLineItem, OptionalLineItem):
    pass
