# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.card_data import CardData
from helcim_python_sdk.type.payment_request import PaymentRequest

PurchaseRequest = typing.Union[PaymentRequest,CardData]
