# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSuccessfulPaymentResponse(TypedDict):
    pass

class OptionalSuccessfulPaymentResponse(TypedDict, total=False):
    # The transaction id
    transactionId: typing.Union[int, float]

    # The id of associated card batch
    cardBatchId: typing.Union[int, float]

    # The date(Mountain Time) when the transaction is created.
    dateCreated: str

    # The status of the transaction. possible values are APPROVED | DECLINED
    status: str

    # Full name of the user who processed the transaction. Default value is Helcim System
    user: str

    # The type of the transaction. possible values are purchase | preauth | verify
    type: str

    # The amount of processed transaction
    amount: typing.Union[int, float]

    # The abbreviation of the transaction's currency
    currency: str

    # AVS Response
    avsResponse: str

    # CVV Response
    cvvResponse: str

    # Approval Code
    approvalCode: str

    # Card token associated to the transaction
    cardToken: str

    # First-6 Last-4 numbers of the card number associated to the transaction
    cardNumber: str

    # Cardholdername associated to the transaction
    cardHolderName: str

    # Customer code associated to the transaction
    customerCode: str

    # Invoice number associated to the transaction
    invoiceNumber: str

    # Warnings
    warning: str

class SuccessfulPaymentResponse(RequiredSuccessfulPaymentResponse, OptionalSuccessfulPaymentResponse):
    pass
