# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from helcim_python_sdk.type.address import Address
from helcim_python_sdk.type.card import Card
from helcim_python_sdk.type.verify_request_invoice import VerifyRequestInvoice

class RequiredVerifyRequest(TypedDict):
    # IP address of the customer making the transaction, used as part of fraud detection.
    ipAddress: str

    # The currency abbreviation of the transaction.
    currency: str

    cardData: Card

    billingAddress: Address

class OptionalVerifyRequest(TypedDict, total=False):
    # Set to indicate that the transaction is e-commerce. When set, the Helcim Fraud Defender will provide further analysis.
    ecommerce: bool

    # Existing customer code associated with the transaction
    customerCode: str

    # To be filled when associating transaction to existing invoice. Invoice should be associated to the same customer linked to the card
    invoiceNumber: str

    invoice: VerifyRequestInvoice

class VerifyRequest(RequiredVerifyRequest, OptionalVerifyRequest):
    pass
