# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from helcim_python_sdk import schemas  # noqa: F401


class PaymentRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "cardData",
            "amount",
            "ipAddress",
            "currency",
        }
        
        class properties:
            ipAddress = schemas.StrSchema
            currency = schemas.StrSchema
            amount = schemas.NumberSchema
            ecommerce = schemas.BoolSchema
            terminalId = schemas.IntSchema
            customerCode = schemas.StrSchema
            invoiceNumber = schemas.StrSchema
        
            @staticmethod
            def invoice() -> typing.Type['PaymentRequestInvoice']:
                return PaymentRequestInvoice
        
            @staticmethod
            def billingAddress() -> typing.Type['Address']:
                return Address
            __annotations__ = {
                "ipAddress": ipAddress,
                "currency": currency,
                "amount": amount,
                "ecommerce": ecommerce,
                "terminalId": terminalId,
                "customerCode": customerCode,
                "invoiceNumber": invoiceNumber,
                "invoice": invoice,
                "billingAddress": billingAddress,
            }
    
    cardData: schemas.AnyTypeSchema
    amount: MetaOapg.properties.amount
    ipAddress: MetaOapg.properties.ipAddress
    currency: MetaOapg.properties.currency
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ipAddress"]) -> MetaOapg.properties.ipAddress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ecommerce"]) -> MetaOapg.properties.ecommerce: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["terminalId"]) -> MetaOapg.properties.terminalId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customerCode"]) -> MetaOapg.properties.customerCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["invoiceNumber"]) -> MetaOapg.properties.invoiceNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["invoice"]) -> 'PaymentRequestInvoice': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billingAddress"]) -> 'Address': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["ipAddress", "currency", "amount", "ecommerce", "terminalId", "customerCode", "invoiceNumber", "invoice", "billingAddress", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ipAddress"]) -> MetaOapg.properties.ipAddress: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["currency"]) -> MetaOapg.properties.currency: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ecommerce"]) -> typing.Union[MetaOapg.properties.ecommerce, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["terminalId"]) -> typing.Union[MetaOapg.properties.terminalId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customerCode"]) -> typing.Union[MetaOapg.properties.customerCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["invoiceNumber"]) -> typing.Union[MetaOapg.properties.invoiceNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["invoice"]) -> typing.Union['PaymentRequestInvoice', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billingAddress"]) -> typing.Union['Address', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["ipAddress", "currency", "amount", "ecommerce", "terminalId", "customerCode", "invoiceNumber", "invoice", "billingAddress", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        cardData: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        amount: typing.Union[MetaOapg.properties.amount, decimal.Decimal, int, float, ],
        ipAddress: typing.Union[MetaOapg.properties.ipAddress, str, ],
        currency: typing.Union[MetaOapg.properties.currency, str, ],
        ecommerce: typing.Union[MetaOapg.properties.ecommerce, bool, schemas.Unset] = schemas.unset,
        terminalId: typing.Union[MetaOapg.properties.terminalId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        customerCode: typing.Union[MetaOapg.properties.customerCode, str, schemas.Unset] = schemas.unset,
        invoiceNumber: typing.Union[MetaOapg.properties.invoiceNumber, str, schemas.Unset] = schemas.unset,
        invoice: typing.Union['PaymentRequestInvoice', schemas.Unset] = schemas.unset,
        billingAddress: typing.Union['Address', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentRequest':
        return super().__new__(
            cls,
            *args,
            cardData=cardData,
            amount=amount,
            ipAddress=ipAddress,
            currency=currency,
            ecommerce=ecommerce,
            terminalId=terminalId,
            customerCode=customerCode,
            invoiceNumber=invoiceNumber,
            invoice=invoice,
            billingAddress=billingAddress,
            _configuration=_configuration,
            **kwargs,
        )

from helcim_python_sdk.model.address import Address
from helcim_python_sdk.model.payment_request_invoice import PaymentRequestInvoice
