# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Address(BaseModel):
    # Contact Name or Business Name
    name: str = Field(alias='name')

    street1: str = Field(alias='street1')

    postal_code: str = Field(alias='postalCode')

    street2: typing.Optional[str] = Field(None, alias='street2')

    city: typing.Optional[str] = Field(None, alias='city')

    # 2 letter abbreviation of the province(AB, BC, CA). Required field if country is CAN or USA.
    province: typing.Optional[str] = Field(None, alias='province')

    # 3-letter abbreviation of the country(CAN, USA)
    country: typing.Optional[str] = Field(None, alias='country')

    # 10 to 15 digits phone number.
    phone: typing.Optional[str] = Field(None, alias='phone')

    email: typing.Optional[str] = Field(None, alias='email')
    class Config:
        arbitrary_types_allowed = True
