# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from helcim_python_sdk.pydantic.address import Address

class BankAccountResponse(BaseModel):
    # The id of the bank account.
    id: typing.Optional[int] = Field(None, alias='id')

    # The id of the customer owning the bank account.
    customer_id: typing.Optional[int] = Field(None, alias='customerId')

    # The date when the bank account is created.
    date_created: typing.Optional[str] = Field(None, alias='dateCreated')

    # The date when the bank account last got updated.
    date_updated: typing.Optional[str] = Field(None, alias='dateUpdated')

    # The date when the bank account last got used.
    date_last_used: typing.Optional[str] = Field(None, alias='dateLastUsed')

    # The date when the bank account is verified.
    date_verified: typing.Optional[str] = Field(None, alias='dateVerified')

    # The token of the bank account.
    bank_token: typing.Optional[str] = Field(None, alias='bankToken')

    # The type of the bank account, such as CHECKING | SAVINGS.
    account_type: typing.Optional[str] = Field(None, alias='accountType')

    # The corporate type of the bank account, such as PERSONAL | CORPORATE.
    account_corporate: typing.Optional[str] = Field(None, alias='accountCorporate')

    # Verified status of the bank account, 1|0.
    verified: typing.Optional[str] = Field(None, alias='verified')

    # Ready status of the bank account, 1|0.
    ready: typing.Optional[str] = Field(None, alias='ready')

    # The institution number of Canadian Bank Account that identifies the bank.
    bank_id_number: typing.Optional[str] = Field(None, alias='bankIdNumber')

    # The transit number of Canadian Bank Account. Shows which branch you opened your account at.
    transit_number: typing.Optional[str] = Field(None, alias='transitNumber')

    # The routing number of US Bank Account. Identifies the financial institution on which it was drawn.
    routing_number: typing.Optional[str] = Field(None, alias='routingNumber')

    # Last 4 digits of the bank account number.
    bank_account_number_l4: typing.Optional[str] = Field(None, alias='bankAccountNumberL4')

    address: typing.Optional[Address] = Field(None, alias='address')
    class Config:
        arbitrary_types_allowed = True
