# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Card1(BaseModel):
    # The card holder name.
    card_holder_name: typing.Optional[str] = Field(None, alias='cardHolderName')

    # The F6L4 of card.
    card_f6_l4: typing.Optional[str] = Field(None, alias='cardF6L4')

    # Card token
    card_token: typing.Optional[str] = Field(None, alias='cardToken')
    class Config:
        arbitrary_types_allowed = True
