# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CardTerminalAddress(BaseModel):
    street1: typing.Optional[str] = Field(None, alias='street1')

    street2: typing.Optional[str] = Field(None, alias='street2')

    city: typing.Optional[str] = Field(None, alias='city')

    # Abbreviation of province
    province: typing.Optional[str] = Field(None, alias='province')

    # Abbreviation of country
    country: typing.Optional[str] = Field(None, alias='country')

    # Postal or zip code
    postal_code: typing.Optional[str] = Field(None, alias='postalCode')
    class Config:
        arbitrary_types_allowed = True
