# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CardTerminalsRequest(BaseModel):
    # The abbreviation of card terminal's currency. Possible values are CAD | USD
    currency: typing.Optional[str] = Field(None, alias='currency')

    # The card terminal's status. possible values are ACTIVE | INACTIVE
    status: typing.Optional[str] = Field(None, alias='status')
    class Config:
        arbitrary_types_allowed = True
