# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Card(BaseModel):
    # The full card number (13 to 16 digits) from merchant to process \"purchase\", \"pre-auth\", and \"verify\" transactions.
    card_number: str = Field(alias='cardNumber')

    # The card expiry date, in MMYY format (total of 4 digits without spaces or slashes).
    card_expiry: str = Field(alias='cardExpiry')

    # The card CVV (3-4 digits on back of credit card).
    card_c_v_v: str = Field(alias='cardCVV')
    class Config:
        arbitrary_types_allowed = True
