# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from helcim_python_sdk.pydantic.card_terminal_address import CardTerminalAddress

class CardTerminal(BaseModel):
    # Id of the terminal.
    id: typing.Optional[int] = Field(None, alias='id')

    # Nickname of terminal
    nickname: typing.Optional[str] = Field(None, alias='nickname')

    # Currency of terminal. possible values are CAD | USD
    currency: typing.Optional[str] = Field(None, alias='currency')

    # Status of Terminal. possible values are ACTIVE | INACTIVE
    status: typing.Optional[str] = Field(None, alias='status')

    address: typing.Optional[CardTerminalAddress] = Field(None, alias='address')
    class Config:
        arbitrary_types_allowed = True
