# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CardResponse(BaseModel):
    # The id of the card.
    id: typing.Optional[int] = Field(None, alias='id')

    # The card token.
    card_token: typing.Optional[str] = Field(None, alias='cardToken')

    # The date when the card is created.
    date_created: typing.Optional[str] = Field(None, alias='dateCreated')

    # The date when the card last got updated.
    date_updated: typing.Optional[str] = Field(None, alias='dateUpdated')

    # The cardholder name.
    card_holder_name: typing.Optional[str] = Field(None, alias='cardHolderName')

    # The first-six and last-four card numbers.
    card_f6_l4: typing.Optional[str] = Field(None, alias='cardF6L4')

    # The card expiry date, in MMYY format (total of 4 digits without spaces or slashes).
    card_expiry: typing.Optional[str] = Field(None, alias='cardExpiry')

    # The card CVV (3-4 digits on back of credit card).
    card_c_v_v: typing.Optional[str] = Field(None, alias='cardCVV')
    class Config:
        arbitrary_types_allowed = True
