# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from helcim_python_sdk.pydantic.address import Address

class CustomerUpdateRequest(BaseModel):
    # The unique customer code.
    customer_code: typing.Optional[str] = Field(None, alias='customerCode')

    # The primary contact name (full name) of the customer.
    contact_name: typing.Optional[str] = Field(None, alias='contactName')

    # The business name of the customer. There must be either a contact name or business name present.
    business_name: typing.Optional[str] = Field(None, alias='businessName')

    # The cell phone number of the customer.
    cell_phone: typing.Optional[str] = Field(None, alias='cellPhone')

    billing_address: typing.Optional[Address] = Field(None, alias='billingAddress')

    shipping_address: typing.Optional[Address] = Field(None, alias='shippingAddress')
    class Config:
        arbitrary_types_allowed = True
