# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class InvoiceBase(BaseModel):
    # Invoice number of invoice to be created. Will be generated if blank
    invoice_number: typing.Optional[str] = Field(None, alias='invoiceNumber')

    # Tip amount
    tip_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='tipAmount')

    # Deposit amount
    deposit_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='depositAmount')

    # Comment to appear at the bottom of the invoice, visible to the customer.
    notes: typing.Optional[str] = Field(None, alias='notes')
    class Config:
        arbitrary_types_allowed = True
