# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class LineItem(BaseModel):
    description: str = Field(alias='description')

    # The quantity of the line item. Can have upto 2 decimal places
    quantity: typing.Union[int, float] = Field(alias='quantity')

    price: typing.Union[int, float] = Field(alias='price')

    # Total = Price * Quantity
    total: typing.Union[int, float] = Field(alias='total')

    sku: typing.Optional[str] = Field(None, alias='sku')

    # This will be added to Invoice's total tax amount
    tax_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='taxAmount')

    # This will be added to Invoice's total discount amount
    discount_amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='discountAmount')
    class Config:
        arbitrary_types_allowed = True
