# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from helcim_python_sdk.pydantic.address import Address
from helcim_python_sdk.pydantic.payment_request_invoice import PaymentRequestInvoice

class PaymentRequest(BaseModel):
    # IP address of the customer making the transaction, used as part of fraud detection.
    ip_address: str = Field(alias='ipAddress')

    # The currency abbreviation of the invoice, such as CAD or USD. This should match currency of existing invoice.
    currency: str = Field(alias='currency')

    # Amount to be processed
    amount: typing.Union[int, float] = Field(alias='amount')

    # Set to indicate that the transaction is e-commerce. When set, the Helcim Fraud Defender will provide further analysis.
    ecommerce: typing.Optional[bool] = Field(None, alias='ecommerce')

    # For card transactions only. Id of the terminal you would want to use. Default terminal for of the currency will be used if you dont send this.
    terminal_id: typing.Optional[int] = Field(None, alias='terminalId')

    # Existing customer code associated with the transaction
    customer_code: typing.Optional[str] = Field(None, alias='customerCode')

    # To be filled when associating transaction to existing invoice. Invoice should be associated to the same customer linked to the card
    invoice_number: typing.Optional[str] = Field(None, alias='invoiceNumber')

    invoice: typing.Optional[PaymentRequestInvoice] = Field(None, alias='invoice')

    billing_address: typing.Optional[Address] = Field(None, alias='billingAddress')
    class Config:
        arbitrary_types_allowed = True
