# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from helcim_python_sdk.pydantic.address import Address

class Shipping(BaseModel):
    # Total Shipping Amount of the Invoice
    amount: typing.Union[int, float] = Field(alias='amount')

    # This will show up in the invoice
    details: str = Field(alias='details')

    address: Address = Field(alias='address')
    class Config:
        arbitrary_types_allowed = True
