# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SuccessfulAchTransactionResponse(BaseModel):
    # The transaction id
    transaction_id: typing.Optional[typing.Union[int, float]] = Field(None, alias='transactionId')

    # The id of associated card batch
    batch_id: typing.Optional[typing.Union[int, float]] = Field(None, alias='batchId')

    # The date(Mountain Time) when the transaction is created.
    date_created: typing.Optional[str] = Field(None, alias='dateCreated')

    # The status of the transaction. possible values are APPROVED | DECLINED | IN_PROGRESS | CANCELLED | PENDING
    status_auth: typing.Optional[str] = Field(None, alias='statusAuth')

    # The status of the transaction. possible values are OPENED | CLEARED | REJECTED | CONTESTED | RETURNED
    status_clearing: typing.Optional[str] = Field(None, alias='statusClearing')

    # The type of the transaction. possible values are WITHDRAWAL | DEPOSIT | SETTLE | REVERSE | REFUND
    type: typing.Optional[str] = Field(None, alias='type')

    # The amount of processed transaction
    amount: typing.Optional[typing.Union[int, float]] = Field(None, alias='amount')

    # The abbreviation of the transaction's currency
    currency: typing.Optional[str] = Field(None, alias='currency')

    # Approval Code
    approval_code: typing.Optional[str] = Field(None, alias='approvalCode')

    # Bank account number
    bank_account_number: typing.Optional[str] = Field(None, alias='bankAccountNumber')

    # Bank Token associated with bankAccount
    bank_token: typing.Optional[str] = Field(None, alias='bankToken')

    # Invoice number associated to the transaction
    invoice_number: typing.Optional[str] = Field(None, alias='invoiceNumber')
    class Config:
        arbitrary_types_allowed = True
