# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from helcim_python_sdk.pydantic.address import Address
from helcim_python_sdk.pydantic.card import Card
from helcim_python_sdk.pydantic.verify_request_invoice import VerifyRequestInvoice

class VerifyRequest(BaseModel):
    # IP address of the customer making the transaction, used as part of fraud detection.
    ip_address: str = Field(alias='ipAddress')

    # The currency abbreviation of the transaction.
    currency: str = Field(alias='currency')

    card_data: Card = Field(alias='cardData')

    billing_address: Address = Field(alias='billingAddress')

    # Set to indicate that the transaction is e-commerce. When set, the Helcim Fraud Defender will provide further analysis.
    ecommerce: typing.Optional[bool] = Field(None, alias='ecommerce')

    # Existing customer code associated with the transaction
    customer_code: typing.Optional[str] = Field(None, alias='customerCode')

    # To be filled when associating transaction to existing invoice. Invoice should be associated to the same customer linked to the card
    invoice_number: typing.Optional[str] = Field(None, alias='invoiceNumber')

    invoice: typing.Optional[VerifyRequestInvoice] = Field(None, alias='invoice')
    class Config:
        arbitrary_types_allowed = True
