# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.card_transactions.get import CollectTransactionsRaw
from helcim_python_sdk.paths.card_transactions_card_transaction_id.get import GetByIdRaw


class CardTransactionApiRaw(
    CollectTransactionsRaw,
    GetByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
