# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.card_terminals.get import GetAll
from helcim_python_sdk.apis.tags.card_terminal_api_raw import CardTerminalApiRaw


class CardTerminalApi(
    GetAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CardTerminalApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CardTerminalApiRaw(api_client)
