# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.card_batches.get import GetAllRaw
from helcim_python_sdk.paths.card_batches_card_batch_id.get import GetDetailsRaw
from helcim_python_sdk.paths.card_batches_card_batch_id_settle.post import SettleBatchRaw


class CardBatchApiRaw(
    GetAllRaw,
    GetDetailsRaw,
    SettleBatchRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
