# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.customers.post import CreateNewCustomerRaw
from helcim_python_sdk.paths.customers_customer_id_bank_accounts_bank_account_id.get import GetBankAccountRaw
from helcim_python_sdk.paths.customers_customer_id_bank_accounts.get import GetBankAccountsRaw
from helcim_python_sdk.paths.customers_customer_id_cards_card_id.get import GetCardDetailsRaw
from helcim_python_sdk.paths.customers_customer_id_cards.get import GetCardsRaw
from helcim_python_sdk.paths.customers_customer_id.get import GetCustomerRaw
from helcim_python_sdk.paths.customers.get import ListRaw
from helcim_python_sdk.paths.customers_customer_id_bank_accounts_bank_account_id_default.patch import SetBankAccountDefaultRaw
from helcim_python_sdk.paths.customers_customer_id.put import UpdateDetailsRaw


class CustomerApiRaw(
    CreateNewCustomerRaw,
    GetBankAccountRaw,
    GetBankAccountsRaw,
    GetCardDetailsRaw,
    GetCardsRaw,
    GetCustomerRaw,
    ListRaw,
    SetBankAccountDefaultRaw,
    UpdateDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
