# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.customers.post import CreateNewCustomer
from helcim_python_sdk.paths.customers_customer_id_bank_accounts_bank_account_id.get import GetBankAccount
from helcim_python_sdk.paths.customers_customer_id_bank_accounts.get import GetBankAccounts
from helcim_python_sdk.paths.customers_customer_id_cards_card_id.get import GetCardDetails
from helcim_python_sdk.paths.customers_customer_id_cards.get import GetCards
from helcim_python_sdk.paths.customers_customer_id.get import GetCustomer
from helcim_python_sdk.paths.customers.get import List
from helcim_python_sdk.paths.customers_customer_id_bank_accounts_bank_account_id_default.patch import SetBankAccountDefault
from helcim_python_sdk.paths.customers_customer_id.put import UpdateDetails
from helcim_python_sdk.apis.tags.customer_api_raw import CustomerApiRaw


class CustomerApi(
    CreateNewCustomer,
    GetBankAccount,
    GetBankAccounts,
    GetCardDetails,
    GetCards,
    GetCustomer,
    List,
    SetBankAccountDefault,
    UpdateDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CustomerApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CustomerApiRaw(api_client)
