# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.connection_test.get import TestConnectivityToHelcimApi
from helcim_python_sdk.apis.tags.general_api_raw import GeneralApiRaw


class GeneralApi(
    TestConnectivityToHelcimApi,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GeneralApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GeneralApiRaw(api_client)
