# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.helcim_pay_initialize.post import CreateCheckoutSession
from helcim_python_sdk.apis.tags.helcim_pay_api_raw import HelcimPayApiRaw


class HelcimPayApi(
    CreateCheckoutSession,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HelcimPayApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HelcimPayApiRaw(api_client)
