# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.helcim_pay_initialize.post import CreateCheckoutSessionRaw


class HelcimPayApiRaw(
    CreateCheckoutSessionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
