# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.invoices.post import CreateNew
from helcim_python_sdk.paths.invoices_invoice_id.get import GetById
from helcim_python_sdk.paths.invoices.get import List
from helcim_python_sdk.paths.invoices_invoice_id.put import UpdateDetails
from helcim_python_sdk.apis.tags.invoice_api_raw import InvoiceApiRaw


class InvoiceApi(
    CreateNew,
    GetById,
    List,
    UpdateDetails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InvoiceApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InvoiceApiRaw(api_client)
