# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.payment_capture.post import ProcessCaptureTransaction
from helcim_python_sdk.paths.payment_preauth.post import ProcessPreauthTransaction
from helcim_python_sdk.paths.payment_purchase.post import ProcessPurchaseTransaction
from helcim_python_sdk.paths.payment_refund.post import ProcessRefundTransaction
from helcim_python_sdk.paths.payment_withdraw.post import ProcessWithdrawalTransaction
from helcim_python_sdk.paths.payment_reverse.post import ReverseTransaction
from helcim_python_sdk.paths.payment_verify.post import VerifyTransaction
from helcim_python_sdk.apis.tags.payment_api_raw import PaymentApiRaw


class PaymentApi(
    ProcessCaptureTransaction,
    ProcessPreauthTransaction,
    ProcessPurchaseTransaction,
    ProcessRefundTransaction,
    ProcessWithdrawalTransaction,
    ReverseTransaction,
    VerifyTransaction,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PaymentApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PaymentApiRaw(api_client)
