# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

from helcim_python_sdk.paths.payment_capture.post import ProcessCaptureTransactionRaw
from helcim_python_sdk.paths.payment_preauth.post import ProcessPreauthTransactionRaw
from helcim_python_sdk.paths.payment_purchase.post import ProcessPurchaseTransactionRaw
from helcim_python_sdk.paths.payment_refund.post import ProcessRefundTransactionRaw
from helcim_python_sdk.paths.payment_withdraw.post import ProcessWithdrawalTransactionRaw
from helcim_python_sdk.paths.payment_reverse.post import ReverseTransactionRaw
from helcim_python_sdk.paths.payment_verify.post import VerifyTransactionRaw


class PaymentApiRaw(
    ProcessCaptureTransactionRaw,
    ProcessPreauthTransactionRaw,
    ProcessPurchaseTransactionRaw,
    ProcessRefundTransactionRaw,
    ProcessWithdrawalTransactionRaw,
    ReverseTransactionRaw,
    VerifyTransactionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
