# coding: utf-8

"""
    The Helcim API

    This API covers publicly accessible merchant actions

    The version of the OpenAPI document: 2.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import helcim_python_sdk
from helcim_python_sdk.paths.customers_customer_id_bank_accounts_bank_account_id_default import patch
from helcim_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestCustomersCustomerIdBankAccountsBankAccountIdDefault(ApiTestMixin, unittest.TestCase):
    """
    CustomersCustomerIdBankAccountsBankAccountIdDefault unit test stubs
        Set customer bank account as default
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
